In [1]:
import pandas as pd
import numpy as np
from yelpapi import YelpAPI
from config import api_key, client_id

With school zip codes can query yelp api,

In [2]:

yelp_api = YelpAPI(api_key)


client_id = client_id
api_key = api_key

# what is distance units from yelp api? 

## look up liquor stores/ grovery stores /

## look at east palo alto versus palo alto and see if ratio looks different or not, need to find distance 
## that I can relate from the school / how far and what kind of stores should I relate to each school? 
# do any of the ratios created correlate with the mean score? 
## look at nulls per county to see if there are target areas that need to be cleaned up or re eval as sf is 
missing hella scores 
##

In [4]:
yelp_data=[]
# maybe make this an empty data frame then concat each one to the next
# shape of results being variable could make this messy ? 
# says as each copy ois made better to lake list then concat list once 
for ZIP in zipcodes: ## list from data set with zipcodes 
    zip_info={} # dict 
    for buiness in community: # list of areas 
        term = buiness
        location = ZIP
        search_limit = 50
        response = yelp_api.search_query(term = term,
                                 location = location,
                                 limit = search_limit)
        cols = list(response['businesses'][0].keys())
        data = pd.DataFrame(columns=cols)
        for biz in response['businesses']:
            data = data.append(biz, ignore_index=True)
        data.head()

NameError: name 'zipcodes' is not defined

In [48]:
term = 'grocery store'
location = '96087'
search_limit = 50
response = yelp_api.search_query(term = term,
                                 location = location,
                                 limit = search_limit)
cols = list(response['businesses'][0].keys())
data = pd.DataFrame(columns=cols)
for biz in response['businesses']:
    data = data.append(biz, ignore_index=True)
data.head()

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,Au225Drt0-ENomQWANYcog,mountain-market-place-weaverville,Mountain Market Place,https://s3-media4.fl.yelpcdn.com/bphoto/iVsDTD...,False,https://www.yelp.com/biz/mountain-market-place...,9,"[{'alias': 'grocery', 'title': 'Grocery'}, {'a...",4.5,"{'latitude': 40.7335714218449, 'longitude': -1...",[],$$,"{'address1': '508 Main St', 'address2': None, ...",+15306232656,(530) 623-2656,29514.825596
1,ALflIN5VVW8qThUvp0bERA,lakeshore-villa-market-lakehead,Lakeshore Villa Market,https://s3-media2.fl.yelpcdn.com/bphoto/dL77SA...,False,https://www.yelp.com/biz/lakeshore-villa-marke...,4,"[{'alias': 'grocery', 'title': 'Grocery'}]",4.5,"{'latitude': 40.88778, 'longitude': -122.3851}",[],$$,"{'address1': '20750 Lakeshore Dr', 'address2':...",+15302388615,(530) 238-8615,34128.249553
2,a-vugKAGBOdGAw0v_YEjQA,tops-super-foods-weaverville,Tops Super Foods,https://s3-media4.fl.yelpcdn.com/bphoto/yo-W99...,False,https://www.yelp.com/biz/tops-super-foods-weav...,30,"[{'alias': 'grocery', 'title': 'Grocery'}]",3.0,"{'latitude': 40.72085, 'longitude': -122.92732}",[],$$$,"{'address1': '1665 Main St', 'address2': '', '...",+15306232494,(530) 623-2494,27913.036988
3,LmwxevWbmqMPm4PD3eqPVg,holiday-market-weaverville,Holiday Market,https://s3-media2.fl.yelpcdn.com/bphoto/jLZjlD...,False,https://www.yelp.com/biz/holiday-market-weaver...,7,"[{'alias': 'grocery', 'title': 'Grocery'}]",3.5,"{'latitude': 40.72103, 'longitude': -122.927216}",[],NaN,"{'address1': '1665 S Main St', 'address2': Non...",+15306232494,(530) 623-2494,27935.143674
4,pBf7hz2kVGuniOgrShOdBA,js-market-shasta,J's Market,https://s3-media1.fl.yelpcdn.com/bphoto/C9TGZ6...,False,https://www.yelp.com/biz/js-market-shasta?adju...,4,"[{'alias': 'grocery', 'title': 'Grocery'}]",5.0,"{'latitude': 40.5967445373535, 'longitude': -1...",[],$$,"{'address1': '15438 Highway 299 W', 'address2'...",+15302433080,(530) 243-3080,11620.018818

In [50]:
term = 'liquor'
location = '96087'
search_limit = 50
response = yelp_api.search_query(term = term,
                                 location = location,
                                 limit = search_limit)
cols = list(response['businesses'][0].keys())
data = pd.DataFrame(columns=cols)
for biz in response['businesses']:
    data = data.append(biz, ignore_index=True)
data.head()

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,Ly30G_29CAUBfFcWK6ehCg,liquor-barn-redding,Liquor Barn,https://s3-media4.fl.yelpcdn.com/bphoto/pjVhfk...,False,https://www.yelp.com/biz/liquor-barn-redding?a...,42,"[{'alias': 'beer_and_wine', 'title': 'Beer, Wi...",4.0,"{'latitude': 40.5692232043026, 'longitude': -1...",[],$$,"{'address1': '2627 Bechelli Ln', 'address2': '...",+15302230452,(530) 223-0452,22701.205429
1,ALflIN5VVW8qThUvp0bERA,lakeshore-villa-market-lakehead,Lakeshore Villa Market,https://s3-media2.fl.yelpcdn.com/bphoto/dL77SA...,False,https://www.yelp.com/biz/lakeshore-villa-marke...,4,"[{'alias': 'grocery', 'title': 'Grocery'}]",4.5,"{'latitude': 40.88778, 'longitude': -122.3851}",[],$$,"{'address1': '20750 Lakeshore Dr', 'address2':...",+15302388615,(530) 238-8615,34128.249553
2,AIx0c_sSBI642Xdfz76jcQ,lakewood-market-redding,Lakewood Market,https://s3-media2.fl.yelpcdn.com/bphoto/uWh4WA...,False,https://www.yelp.com/biz/lakewood-market-reddi...,3,"[{'alias': 'beer_and_wine', 'title': 'Beer, Wi...",5.0,"{'latitude': 40.6195, 'longitude': -122.39745}",[],$,"{'address1': '901 Lake Blvd', 'address2': 'Ste...",+15302414997,(530) 241-4997,18507.755856
3,7KiwL7Tx5N9xED7Dsv74kQ,duffys-liquors-anderson,Duffy's Liquors,https://s3-media2.fl.yelpcdn.com/bphoto/mZGTSV...,False,https://www.yelp.com/biz/duffys-liquors-anders...,10,"[{'alias': 'beer_and_wine', 'title': 'Beer, Wi...",3.5,"{'latitude': 40.452844, 'longitude': -122.299132}",[],$$$,"{'address1': '2182 North St', 'address2': None...",+15303657050,(530) 365-7050,33594.167953
4,W2jVpz7gb9RQx9jmJM7s5w,liquor-king-redding,Liquor King,https://s3-media2.fl.yelpcdn.com/bphoto/rp3iMF...,False,https://www.yelp.com/biz/liquor-king-redding?a...,2,"[{'alias': 'beer_and_wine', 'title': 'Beer, Wi...",3.5,"{'latitude': 40.5616149902344, 'longitude': -1...",[],NaN,"{'address1': '3136 Bechelli Ln', 'address2': '...",+15302211069,(530) 221-1069,22873.685662

In [47]:
term = 'grocery store'
location = '94116'
search_limit = 50
response = yelp_api.search_query(term = term,
                                 location = location,
                                 limit = search_limit)
cols = list(response['businesses'][0].keys())
data = pd.DataFrame(columns=cols)
for biz in response['businesses']:
    data = data.append(biz, ignore_index=True)
data.head()

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,bbDXbRE6O8BUbK3nyXdGCg,guss-community-market-san-francisco-6,Gus's Community Market,https://s3-media3.fl.yelpcdn.com/bphoto/AzXDW1...,False,https://www.yelp.com/biz/guss-community-market...,311,"[{'alias': 'markets', 'title': 'Fruits & Veggi...",4.5,"{'latitude': 37.75281, 'longitude': -122.50357}","[pickup, delivery]",$$,"{'address1': '3701 Noriega St', 'address2': 'U...",+14155640370,(415) 564-0370,1728.843896
1,KBsTJh5FVV_JQEVYvTDCWg,safeway-san-francisco-11,Safeway,https://s3-media2.fl.yelpcdn.com/bphoto/P3fTlr...,False,https://www.yelp.com/biz/safeway-san-francisco...,259,"[{'alias': 'grocery', 'title': 'Grocery'}]",2.5,"{'latitude': 37.754172, 'longitude': -122.4888...",[],$$,"{'address1': '2350 Noriega St', 'address2': ''...",+14156654565,(415) 665-4565,688.666558
2,t2BIu94PpNJqzxKw18c4VQ,lucky-san-francisco-3,Lucky,https://s3-media1.fl.yelpcdn.com/bphoto/zaSSYz...,False,https://www.yelp.com/biz/lucky-san-francisco-3...,224,"[{'alias': 'grocery', 'title': 'Grocery'}, {'a...",3.0,"{'latitude': 37.73304, 'longitude': -122.48955}","[pickup, delivery]",$$,"{'address1': '1515 Sloat Blvd', 'address2': ''...",+14156814300,(415) 681-4300,1815.466998
3,9-Irfu8q-Mm3aEDXY18GbA,sunset-supermarket-san-francisco,Sunset Supermarket,https://s3-media4.fl.yelpcdn.com/bphoto/_qJ44z...,False,https://www.yelp.com/biz/sunset-supermarket-sa...,141,"[{'alias': 'intlgrocery', 'title': 'Internatio...",3.0,"{'latitude': 37.7381096, 'longitude': -122.497...",[],$,"{'address1': '2801 Vicente St', 'address2': ''...",+14155048188,(415) 504-8188,1658.603388
4,C9YDe3DdURTN01ZaTefWWw,safeway-san-francisco-21,Safeway,https://s3-media4.fl.yelpcdn.com/bphoto/srKv5b...,False,https://www.yelp.com/biz/safeway-san-francisco...,260,"[{'alias': 'grocery', 'title': 'Grocery'}]",2.0,"{'latitude': 37.743262, 'longitude': -122.4739...",[],$$,"{'address1': '730 Taraval St', 'address2': '',...",+14156654136,(415) 665-4136,1107.331782

In [45]:
cols = list(response['businesses'][0].keys())
data = pd.DataFrame(columns=cols)
for biz in response['businesses']:
    data = data.append(biz, ignore_index=True)
data.head()

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,BI40rGhpngLNPacrjWpseQ,dumpling-kitchen-san-francisco,Dumpling Kitchen,https://s3-media1.fl.yelpcdn.com/bphoto/rggI1H...,False,https://www.yelp.com/biz/dumpling-kitchen-san-...,1821,"[{'alias': 'chinese', 'title': 'Chinese'}]",4.0,"{'latitude': 37.7423, 'longitude': -122.48701}","[pickup, delivery]",$$,"{'address1': '1935 Taraval St', 'address2': ''...",+14156828938,(415) 682-8938,773.197264
1,5iZp3XBPOUTIqQY7vGAfVA,hotline-san-francisco,Hotline,https://s3-media1.fl.yelpcdn.com/bphoto/Iy0XS0...,False,https://www.yelp.com/biz/hotline-san-francisco...,7,"[{'alias': 'korean', 'title': 'Korean'}, {'ali...",5.0,"{'latitude': 37.74203, 'longitude': -122.50446}",[],NaN,"{'address1': '3560 Taraval St', 'address2': No...",+14157026301,(415) 702-6301,1920.394200
2,DSHzsZwazLD6g4Ot17A3iQ,dim-sum-club-san-francisco-3,Dim Sum Club,https://s3-media1.fl.yelpcdn.com/bphoto/sWhZZ4...,False,https://www.yelp.com/biz/dim-sum-club-san-fran...,133,"[{'alias': 'dimsum', 'title': 'Dim Sum'}, {'al...",4.0,"{'latitude': 37.74224411177974, 'longitude': -...","[restaurant_reservation, delivery, pickup]",$$,"{'address1': '2237 Taraval St', 'address2': ''...",+14155928938,(415) 592-8938,908.906206
3,XhbkZ-5nUJ3bRy7uKPx7iQ,mr-szechuan-san-francisco,Mr Szechuan,https://s3-media3.fl.yelpcdn.com/bphoto/lFs0UW...,False,https://www.yelp.com/biz/mr-szechuan-san-franc...,396,"[{'alias': 'chinese', 'title': 'Chinese'}, {'a...",4.5,"{'latitude': 37.74331, 'longitude': -122.47544}","[pickup, delivery]",$$,"{'address1': '890 Taraval St', 'address2': Non...",+14157538788,(415) 753-8788,1013.585493
4,QL_k7HiTGqvtjrT1SFImqg,noodle-stop-san-francisco,Noodle Stop,https://s3-media4.fl.yelpcdn.com/bphoto/1UsWyH...,False,https://www.yelp.com/biz/noodle-stop-san-franc...,18,"[{'alias': 'noodles', 'title': 'Noodles'}]",4.0,"{'latitude': 37.75395, 'longitude': -122.478}",[],NaN,"{'address1': '1325 Noriega St', 'address2': ''...",+14157536688,(415) 753-6688,798.324388

In [27]:
term = 'Mexican restaurant bar'
location = 'Astoria, NY'
search_limit = 50
response = yelp_api.search_query(term = term,
                                 location = location,
                                 limit = search_limit)
type(response)

dict

In [24]:
cols = list(response['businesses'][0].keys())
data = pd.DataFrame(columns=cols)
for biz in response['businesses']:
    data = data.append(biz, ignore_index=True)
data.head()

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,EHUNrnIgnhwTnpOm3gEESg,tacuba-astoria,Tacuba,https://s3-media2.fl.yelpcdn.com/bphoto/xrzWf3...,False,https://www.yelp.com/biz/tacuba-astoria?adjust...,710,"[{'alias': 'mexican', 'title': 'Mexican'}, {'a...",4.0,"{'latitude': 40.75609, 'longitude': -73.924441}","[pickup, delivery]",$$,"{'address1': '35-01 36th St', 'address2': '', ...",+17187862727,(718) 786-2727,1215.568416
1,yvva7IYpD6J7OfKlCdQrkw,mi-espiguita-taqueria-astoria,Mi Espiguita Taqueria,https://s3-media2.fl.yelpcdn.com/bphoto/TEho39...,False,https://www.yelp.com/biz/mi-espiguita-taqueria...,134,"[{'alias': 'mexican', 'title': 'Mexican'}]",4.5,"{'latitude': 40.7612033639422, 'longitude': -7...","[pickup, delivery]",$,"{'address1': '32-44 31st St', 'address2': '', ...",+17187775648,(718) 777-5648,714.301080
2,YFL1rAdlv7J0cswHVhvCtQ,ruta-oaxaca-mexican-cuisine-astoria,Ruta Oaxaca Mexican Cuisine,https://s3-media2.fl.yelpcdn.com/bphoto/_5Z0dN...,False,https://www.yelp.com/biz/ruta-oaxaca-mexican-c...,179,"[{'alias': 'mexican', 'title': 'Mexican'}]",4.5,"{'latitude': 40.760579, 'longitude': -73.921857}","[pickup, delivery]",$$$,"{'address1': '35-03 Broadway', 'address2': Non...",+19293491228,(929) 349-1228,705.175234
3,kd3yCktupzkZXjI6xDSkqA,orale-mexico-astoria,ORALE MEXICO,https://s3-media2.fl.yelpcdn.com/bphoto/W51EtQ...,False,https://www.yelp.com/biz/orale-mexico-astoria?...,18,"[{'alias': 'mexican', 'title': 'Mexican'}]",5.0,"{'latitude': 40.7702872, 'longitude': -73.9183...","[pickup, delivery]",NaN,"{'address1': '3019 Astoria Blvd', 'address2': ...",+19178327813,(917) 832-7813,494.597826
4,ci0-GO_iMb0NdTCUYWjocQ,noche-de-margaritas-new-york,Noche De Margaritas,https://s3-media1.fl.yelpcdn.com/bphoto/102pyt...,False,https://www.yelp.com/biz/noche-de-margaritas-n...,383,"[{'alias': 'mexican', 'title': 'Mexican'}]",4.0,"{'latitude': 40.7801018, 'longitude': -73.9497...","[pickup, delivery]",$$,"{'address1': '1726 2nd Ave', 'address2': '', '...",+12122895195,(212) 289-5195,2759.294057

In [34]:
## look at table to join yelp too 

df = pd.read_csv('../data/processed/pov_added.csv')

In [35]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,County Code,District Code,School Code,Test Year_x,Student Group ID,Total Tested at Reporting Level,Total Tested with Scores at Reporting Level,...,"Total Students, All Grades (Excludes AE) [District] 2020-21",Full-Time Equivalent (FTE) Teachers [District] 2020-21,Pupil/Teacher Ratio [District] 2020-21,_merge,State Postal Code,State FIPS Code,District ID,Estimated Total Population,Estimated Population 5-17,est_num_u17_pov
0,0,10,121,1,61127,130450,2021,1,217.0,216.0,...,3501.0,166.07,21.08,both,CA,6,1860,20467,3218,168
1,1,11,122,1,61127,130450,2021,1,217.0,216.0,...,3501.0,166.07,21.08,both,CA,6,1860,20467,3218,168
2,2,12,123,1,61127,130450,2021,1,219.0,218.0,...,3501.0,166.07,21.08,both,CA,6,1860,20467,3218,168
3,3,13,124,1,61127,130450,2021,1,219.0,218.0,...,3501.0,166.07,21.08,both,CA,6,1860,20467,3218,168
4,4,14,129,1,61143,131177,2021,1,74.0,74.0,...,9409.0,502.56,18.72,both,CA,6,4740,123764,9695,653

In [36]:
df.sample(4).T

,18218,4047,4545,10036
Unnamed: 0,18218,4047,4545,10036
Unnamed: 0.1,19380,4571,5045,11220
Unnamed: 0.1.1,29907,7736,8452,17778
County Code,45,16,17,31
District Code,70128,63917,64055,66787
School Code,6050546,6010409,1736008,126664
Test Year_x,2021,2021,2021,2021
Student Group ID,1,1,1,1
Total Tested at Reporting Level,67.0,222.0,88.0,83.0
Total Tested with Scores at Reporting Level,65.0,220.0,88.0,83.0
Grade,13,4,11,7
Test ID,NaN,NaN,NaN,NaN
Students Enrolled,70.0,80.0,111.0,NaN
Students Tested,67.0,31.0,88.0,NaN
Mean Scale Score,NaN,2416.5,2538.9,NaN
Percentage Standard Exceeded,7.69,6.67,9.09,NaN
Percentage Standard Met,21.54,16.67,29.55,NaN
Percentage Standard Met and Above,29.23,23.33,38.64,NaN
Percentage Standard Nearly Met,30.77,33.33,29.55,NaN
Percentage Standard Not Met,40.0,43.33,31.82,NaN
Students with Scores,65.0,30.0,88.0,NaN
Area 1 Percentage Above Standard,10.77,6.67,18.18,NaN
Area 1 Percentage Near Standard,49.23,73.33,52.27,NaN
Area 1 Percentage Below Standard,40.0,20.0,29.55,NaN
Area 2 Percentage Above Standard,7.69,10.0,6.82,NaN
Area 2 Percentage Near Standard,55.38,50.0,55.68,NaN
Area 2 Percentage Below Standard,36.92,40.0,37.5,NaN
Area 3 Percentage Above Standard,6.15,3.33,3.41,NaN
Area 3 Percentage Near Standard,66.15,76.67,80.68,NaN
Area 3 Percentage Below Standard,27.69,20.0,15.91,NaN
Area 4 Percentage Above Standard,0.0,13.33,11.36,NaN
Area 4 Percentage Near Standard,0.0,60.0,69.32,NaN
Area 4 Percentage Below Standard,0.0,26.67,19.32,NaN
Type ID_x,7,7,7,10
Test Year_y,2021,2021,2021,2021
Type ID_y,7,7,7,10
County Name,Shasta,Kings,Lake,Placer
District Name,shasta union elementary,hanford elementary,middletown unified,auburn union elementary
School Name,Shasta Elementary,Lee Richmond Elementary,Middletown High,Alta Vista Community Charter
Zip Code,96087.0,93230.0,95461.0,95603.0
State Name [District] Latest available year,California,California,California,California
State Name [District] 2020-21,CALIFORNIA,CALIFORNIA,CALIFORNIA,CALIFORNIA
Agency ID - NCES Assigned [District] Latest available year,636570.0,616470.0,624750.0,603480.0
County Name [District] 2020-21,Shasta County,Kings County,Lake County,Placer County
"Total Students, All Grades (Excludes AE) [District] 2020-21",114.0,5690.0,1391.0,1741.0
Full-Time Equivalent (FTE) Teachers [District] 2020-21,6.4,240.03,67.6,82.75
Pupil/Teacher Ratio [District] 2020-21,17.81,23.71,20.58,21.04
_merge,both,both,both,both
State Postal Code,CA,CA,CA,CA
State FIPS Code,6,6,6,6
District ID,36570,16470,24750,3480
Estimated Total Population,2316,44391,10023,38143
Estimated Population 5-17,222,6660,1778,3343
est_num_u17_pov,32,1161,213,332

In [43]:
df[df['Zip Code']==94116.0].sample(5).T

,14816,14887,14891,14817,14890
Unnamed: 0,14816,14887,14891,14817,14890
Unnamed: 0.1,15215,15286,15290,15216,15289
Unnamed: 0.1.1,23617,23688,23692,23618,23691
County Code,38,38,38,38,38
District Code,68478,68478,68478,68478,68478
School Code,3833241,6059851,6059851,3833241,6059851
Test Year_x,2021,2021,2021,2021,2021
Student Group ID,1,1,1,1,1
Total Tested at Reporting Level,NaN,NaN,NaN,NaN,NaN
Total Tested with Scores at Reporting Level,NaN,NaN,NaN,NaN,NaN
Grade,13,6,8,11,6
Test ID,NaN,NaN,NaN,NaN,NaN
Students Enrolled,486.0,314.0,316.0,486.0,314.0
Students Tested,NaN,NaN,NaN,NaN,NaN
Mean Scale Score,NaN,NaN,NaN,NaN,NaN
Percentage Standard Exceeded,NaN,NaN,NaN,NaN,NaN
Percentage Standard Met,NaN,NaN,NaN,NaN,NaN
Percentage Standard Met and Above,NaN,NaN,NaN,NaN,NaN
Percentage Standard Nearly Met,NaN,NaN,NaN,NaN,NaN
Percentage Standard Not Met,NaN,NaN,NaN,NaN,NaN
Students with Scores,NaN,NaN,NaN,NaN,NaN
Area 1 Percentage Above Standard,NaN,NaN,NaN,NaN,NaN
Area 1 Percentage Near Standard,NaN,NaN,NaN,NaN,NaN
Area 1 Percentage Below Standard,NaN,NaN,NaN,NaN,NaN
Area 2 Percentage Above Standard,NaN,NaN,NaN,NaN,NaN
Area 2 Percentage Near Standard,NaN,NaN,NaN,NaN,NaN
Area 2 Percentage Below Standard,NaN,NaN,NaN,NaN,NaN
Area 3 Percentage Above Standard,NaN,NaN,NaN,NaN,NaN
Area 3 Percentage Near Standard,NaN,NaN,NaN,NaN,NaN
Area 3 Percentage Below Standard,NaN,NaN,NaN,NaN,NaN
Area 4 Percentage Above Standard,NaN,NaN,NaN,NaN,NaN
Area 4 Percentage Near Standard,NaN,NaN,NaN,NaN,NaN
Area 4 Percentage Below Standard,NaN,NaN,NaN,NaN,NaN
Type ID_x,7,7,7,7,7
Test Year_y,2021,2021,2021,2021,2021
Type ID_y,7,7,7,7,7
County Name,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco
District Name,san francisco unified,san francisco unified,san francisco unified,san francisco unified,san francisco unified
School Name,Lincoln (Abraham) High,Hoover (Herbert) Middle,Hoover (Herbert) Middle,Lincoln (Abraham) High,Hoover (Herbert) Middle
Zip Code,94116.0,94116.0,94116.0,94116.0,94116.0
State Name [District] Latest available year,California,California,California,California,California
State Name [District] 2020-21,CALIFORNIA,CALIFORNIA,CALIFORNIA,CALIFORNIA,CALIFORNIA
Agency ID - NCES Assigned [District] Latest available year,634410.0,634410.0,634410.0,634410.0,634410.0
County Name [District] 2020-21,San Francisco County,San Francisco County,San Francisco County,San Francisco County,San Francisco County
"Total Students, All Grades (Excludes AE) [District] 2020-21",51790.0,51790.0,51790.0,51790.0,51790.0
Full-Time Equivalent (FTE) Teachers [District] 2020-21,2501.58,2501.58,2501.58,2501.58,2501.58
Pupil/Teacher Ratio [District] 2020-21,20.7,20.7,20.7,20.7,20.7
_merge,both,both,both,both,both
State Postal Code,CA,CA,CA,CA,CA
State FIPS Code,6,6,6,6,6
District ID,34410,34410,34410,34410,34410
Estimated Total Population,866606,866606,866606,866606,866606
Estimated Population 5-17,78720,78720,78720,78720,78720
est_num_u17_pov,7367,7367,7367,7367,7367